name: gophercon
description: A Helm charts for Kubernetes application
version: 0.0.1
home: https://k8s.community/
sources:
  - https://github.com/skrekkur/gophercon-gokub-ws
maintainers:
  - name: Aevar
    email: skrekkur@gmail.com
engine: gotpl
